repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: linters
    name: Lint
    entry: poetry run python -m tasks lint
    language: system
    types: [python]
  - id: formatters
    name: Format
    entry: poetry run python -m tasks format
    language: system
    types: [python]
