# vim: set ft=yaml ts=2 sw=2:

name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        python: ['3.7', '3.8']
        os: [ubuntu-latest, windows-latest]

    name: Python ${{ matrix.python }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          python -m develop --ci --test-only

      - name: Run tests
        run: poetry run python -m tasks test --coverage

      - name: Generate coverage.xml
        run: poetry run coverage xml

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false  # Setting this to true is a headache.

  lint:
    name: Run static checkers.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          python -m develop --ci

      - name: Run all checks
        run: poetry run python -m tasks static-checks
